### ISSUE TITLE
Upgrade to GraalVM 21.0.0

### ISSUE THREAD

**Issue by usommerl** [usommerl/graalnative4s#51]
I have made an attempt to upgrade to GraalVM v21.0.0 on branch  [feature/upgrade-to-graal-v21.x.x][branch] but the created image fails at runtime:

```
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.invoke.VarHandle.releaseFence()
	at java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:230)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:75)
	at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
	at java.lang.invoke.LambdaForm$MH/1617744704.invoke_MT(LambdaForm$MH)
	at scala.runtime.Statics.releaseFence(Statics.java:148)
	at scala.collection.immutable.$colon$colon.<init>(List.scala:623)
	at scala.collection.immutable.List.prependedAll(List.scala:153)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1258)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1258)
	at scala.collection.AbstractIterable.toList(Iterable.scala:920)
	at cats.effect.internals.IOTracing$.buildFrame(IOTracing.scala:48)
	at cats.effect.internals.IOTracing$.buildCachedFrame(IOTracing.scala:39)
	at cats.effect.internals.IOTracing$.cached(IOTracing.scala:34)
	at cats.effect.IO.flatMap(IO.scala:133)
	at cats.effect.IOLowPriorityInstances$IOEffect.flatMap(IO.scala:886)
	at cats.effect.IOLowPriorityInstances$IOEffect.flatMap(IO.scala:863)
	at cats.FlatMap$Ops.flatMap(FlatMap.scala:229)
	at cats.FlatMap$Ops.flatMap$(FlatMap.scala:229)
	at cats.FlatMap$ToFlatMapOps$$anon$2.flatMap(FlatMap.scala:243)
	at io.odin.loggers.DefaultLogger.$anonfun$log$1(DefaultLogger.scala:23)
	at cats.Applicative.whenA(Applicative.scala:187)
	at cats.Applicative.whenA$(Applicative.scala:186)
	at cats.effect.IOLowPriorityInstances$IOEffect.whenA(IO.scala:863)
	at io.odin.loggers.DefaultLogger.log(DefaultLogger.scala:23)
	at io.odin.loggers.DefaultLogger.$anonfun$info$1(DefaultLogger.scala:98)
	at cats.Applicative.whenA(Applicative.scala:187)
	at cats.Applicative.whenA$(Applicative.scala:186)
	at cats.effect.IOLowPriorityInstances$IOEffect.whenA(IO.scala:863)
	at io.odin.loggers.DefaultLogger.info(DefaultLogger.scala:98)
	at server.Main$.runF(Main.scala:26)
	at server.Main$.run(Main.scala:21)
	at cats.effect.IOApp.$anonfun$main$3(IOApp.scala:69)
	at cats.effect.internals.IOAppPlatform$.mainFiber(IOAppPlatform.scala:45)
	at cats.effect.internals.IOAppPlatform$.main(IOAppPlatform.scala:27)
	at cats.effect.IOApp.main(IOApp.scala:69)
	at cats.effect.IOApp.main$(IOApp.scala:68)
	at server.Main$.main(Main.scala:17)
	at server.Main.main(Main.scala)
```

This is a follow-up of #16 

[branch]: https://github.com/usommerl/graalnative4s/tree/feature/upgrade-to-graal-v21.x.x

**Comment by usommerl** [comment]
I regenerated the native-image configuration files with the GraalVM tracing agent. This resolved the issue above.
See: https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#assisted-configuration-of-native-image-builds
